# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  python-local-tests:
    docker:
      - image: circleci/python:3.5-jessie-browsers
    environment:
    steps:
      - checkout
      - run: wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
      - run: tar -xvzf geckodriver*
      - run: chmod +x geckodriver
      - run: sudo mv geckodriver /usr/local/bin
      - run: sudo pip install selenium
      - run: python selenium/code_bat.py

  python-cloud-tests:
    docker:
      - image: circleci/python:3.5-jessie-browsers
    environment:
    steps:
      - checkout
      - run: sudo pip install selenium
      - run: python selenium/sauce_labs.py


  java-local-tests:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    environment:
    steps:
      - checkout
      - run: mkdir test-reports
      ###################################
      # Download geckodriver
      ###################################
      - run: wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
      - run: tar -xvzf geckodriver*
      - run: chmod +x geckodriver
      - run: sudo mv geckodriver /usr/local/bin
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: sudo apt-get install junit4
      - run: javac -classpath ~/project/selenium-server-standalone-3.5.3.jar ~/project/exams/crowdTwist/*.java
      - run: java -Dbrowser=chrome -cp /home/circleci/project/selenium-server-standalone-3.5.3.jar:/usr/share/java/junit4.jar:/home/circleci/project/exams/crowdTwist/:.  org.junit.runner.JUnitCore CrowdTwistTests      
      #- run: java -Dbrowser=firefox -cp /home/circleci/project/selenium-server-standalone-3.5.3.jar:/usr/share/java/junit4.jar:/home/circleci/project/exams/crowdTwist/:.  org.junit.runner.JUnitCore CrowdTwistTests
      
  java-cloud-tests:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    environment:
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run: sudo apt-get install junit4
      - run: javac -classpath ~/project/selenium-server-standalone-3.5.3.jar ~/project/selenium/TestingBot.java
      - run: java -cp /home/circleci/project/selenium-server-standalone-3.5.3.jar:/usr/share/java/junit4.jar:/home/circleci/project/selenium/:.  org.junit.runner.JUnitCore TestingBot    
      

workflows:
  version: 2
  build-test-all:
    jobs:
      - java-local-tests
      - java-cloud-tests
      - python-local-tests
      - python-cloud-tests