print "game over...try again!"
print "    ____"
print "   |    |"
print "   o    |"
print "  /|\\   |"
print "  / \\   |"
print "        |"
print "        |"
print "  ----------"
print ""
print ""
print ""
print ""